package net.imthebeemoplush.beemoboatsigns.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.imthebeemoplush.beemoboatsigns.block.*;
import net.imthebeemoplush.beemoboatsigns.BeemosBoatSignsMod;

public class BeemosBoatSignsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, BeemosBoatSignsMod.MODID);
	public static final RegistryObject<Block> APPLIES_TO_SHIPS_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> APPLIES_TO_SHIPS_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> APPLIES_TO_SHIPS_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> CABLE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> CABLE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> CABLE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> PIPE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> PIPE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> PIPE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> ANCHORING_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> ANCHORING_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> ANCHORING_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DISPOSAL_STATION_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DISPOSAL_STATION_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DISPOSAL_STATION_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> JET_SKI_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> JET_SKI_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> JET_SKI_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MOORING_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MOORING_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MOORING_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MOTORBOAT_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MOTORBOAT_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MOTORBOAT_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SAILBOATS_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> SAILBOATS_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> SAILBOATS_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> WASHING_PLATFORM_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> WASHING_PLATFORM_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> WASHING_PLATFORM_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> WATER_SKI_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> WATER_SKI_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> WATER_SKI_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> WINDSURFING_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> WINDSURFING_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> WINDSURFING_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> LIANA_SIGN;
	public static final RegistryObject<Block> LIANA_SIGN_1;
	public static final RegistryObject<Block> ANCHORING_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> ANCHORING_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> ANCHORING_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DIVING_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DIVING_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DIVING_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> JET_SKI_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> JET_SKI_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> JET_SKI_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> GOING_ASHORE_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> GOING_ASHORE_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> GOING_ASHORE_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MOORING_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MOORING_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MOORING_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MOTORBOAT_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MOTORBOAT_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MOTORBOAT_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> PARKING_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> PARKING_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> PARKING_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SAILBOATS_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> SAILBOATS_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> SAILBOATS_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> WATER_SKI_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> WATER_SKI_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> WATER_SKI_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> WINDSURFING_PROHIBITED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> WINDSURFING_PROHIBITED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> WINDSURFING_PROHIBITED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> CABLE_FERRY_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> CABLE_FERRY_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> CABLE_FERRY_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> CONSTRUCTION_ZONE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> CONSTRUCTION_ZONE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> CONSTRUCTION_ZONE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> FISHING_GEAR_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> FISHING_GEAR_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> FISHING_GEAR_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> GIVE_SOUND_SIGNAL_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> GIVE_SOUND_SIGNAL_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> GIVE_SOUND_SIGNAL_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> LIVE_WIRE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> LIVE_WIRE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> LIVE_WIRE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MOVEABLE_BRIDGE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MOVEABLE_BRIDGE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MOVEABLE_BRIDGE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> ONE_WAY_TRAFFIC_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> ONE_WAY_TRAFFIC_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> ONE_WAY_TRAFFIC_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> OTHER_HAZARD_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> OTHER_HAZARD_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> OTHER_HAZARD_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> STOP_LINE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> STOP_LINE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> STOP_LINE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SWIMMING_AREA_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> SWIMMING_AREA_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> SWIMMING_AREA_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> MAX_SPEED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> MAX_SPEED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> MAX_SPEED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> REFER_TO_CHART_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> REFER_TO_CHART_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> REFER_TO_CHART_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_M_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_M_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_M_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_NM_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_NM_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DISTANCE_FROM_MARK_NM_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DISTANCE_TO_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DISTANCE_TO_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DISTANCE_TO_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> DIVING_ALLOWED_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> DIVING_ALLOWED_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> DIVING_ALLOWED_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> BOAT_WASHING_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> BOAT_WASHING_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> BOAT_WASHING_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SHORE_POWER_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> SHORE_POWER_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> SHORE_POWER_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> NO_WAKE_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> NO_WAKE_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> NO_WAKE_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> RESTRICTED_HEIGHT_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> RESTRICTED_HEIGHT_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> RESTRICTED_HEIGHT_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> RESTRICTED_WIDTH_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> RESTRICTED_WIDTH_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> RESTRICTED_WIDTH_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> RESTRICTED_DEPTH_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> RESTRICTED_DEPTH_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> RESTRICTED_DEPTH_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> LEADING_LINE_BOTTOM_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> LEADING_LINE_BOTTOM_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> LEADING_LINE_BOTTOM_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> LEADING_LINE_TOP_SEAWAY_MARK_SMALL;
	public static final RegistryObject<Block> LEADING_LINE_TOP_SEAWAY_MARK_MEDIUM;
	public static final RegistryObject<Block> LEADING_LINE_TOP_SEAWAY_MARK_BIG;
	public static final RegistryObject<Block> SIGN_MOUNT_BASE_SMALL;
	public static final RegistryObject<Block> SIGN_MOUNT_BASE_MEDIUM;
	public static final RegistryObject<Block> SIGN_MOUNT_BASE_BIG;
	public static final RegistryObject<Block> SIGN_MOUNT_SMALL;
	public static final RegistryObject<Block> SIGN_MOUNT_MEDIUM;
	public static final RegistryObject<Block> SIGN_MOUNT_BIG;
	public static final RegistryObject<Block> THIN_SIGN_MOUNT_SMALL;
	public static final RegistryObject<Block> THIN_SIGN_MOUNT_MEDIUM;
	public static final RegistryObject<Block> THIN_SIGN_MOUNT_BIG;

	static {
		APPLIES_TO_SHIPS_SEAWAY_MARK_SMALL = REGISTRY.register("applies_to_ships_seaway_mark_small", AppliesToShipsSeawayMarkSmallBlock::new);
		APPLIES_TO_SHIPS_SEAWAY_MARK_MEDIUM = REGISTRY.register("applies_to_ships_seaway_mark_medium", AppliesToShipsSeawayMarkMediumBlock::new);
		APPLIES_TO_SHIPS_SEAWAY_MARK_BIG = REGISTRY.register("applies_to_ships_seaway_mark_big", AppliesToShipsSeawayMarkBigBlock::new);
		DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_SMALL = REGISTRY.register("does_not_apply_to_ships_seaway_mark_small", DoesNotApplyToShipsSeawayMarkSmallBlock::new);
		DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_MEDIUM = REGISTRY.register("does_not_apply_to_ships_seaway_mark_medium", DoesNotApplyToShipsSeawayMarkMediumBlock::new);
		DOES_NOT_APPLY_TO_SHIPS_SEAWAY_MARK_BIG = REGISTRY.register("does_not_apply_to_ships_seaway_mark_big", DoesNotApplyToShipsSeawayMarkBigBlock::new);
		CABLE_SEAWAY_MARK_SMALL = REGISTRY.register("cable_seaway_mark_small", CableSeawayMarkSmallBlock::new);
		CABLE_SEAWAY_MARK_MEDIUM = REGISTRY.register("cable_seaway_mark_medium", CableSeawayMarkMediumBlock::new);
		CABLE_SEAWAY_MARK_BIG = REGISTRY.register("cable_seaway_mark_big", CableSeawayMarkBigBlock::new);
		PIPE_SEAWAY_MARK_SMALL = REGISTRY.register("pipe_seaway_mark_small", PipeSeawayMarkSmallBlock::new);
		PIPE_SEAWAY_MARK_MEDIUM = REGISTRY.register("pipe_seaway_mark_medium", PipeSeawayMarkMediumBlock::new);
		PIPE_SEAWAY_MARK_BIG = REGISTRY.register("pipe_seaway_mark_big", PipeSeawayMarkBigBlock::new);
		ANCHORING_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("anchoring_allowed_seaway_mark_small", AnchoringAllowedSeawayMarkSmallBlock::new);
		ANCHORING_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("anchoring_allowed_seaway_mark_medium", AnchoringAllowedSeawayMarkMediumBlock::new);
		ANCHORING_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("anchoring_allowed_seaway_mark_big", AnchoringAllowedSeawayMarkBigBlock::new);
		DISPOSAL_STATION_SEAWAY_MARK_SMALL = REGISTRY.register("disposal_station_seaway_mark_small", DisposalStationSeawayMarkSmallBlock::new);
		DISPOSAL_STATION_SEAWAY_MARK_MEDIUM = REGISTRY.register("disposal_station_seaway_mark_medium", DisposalStationSeawayMarkMediumBlock::new);
		DISPOSAL_STATION_SEAWAY_MARK_BIG = REGISTRY.register("disposal_station_seaway_mark_big", DisposalStationSeawayMarkBigBlock::new);
		DIVING_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("diving_allowed_seaway_mark_small", DivingAllowedSeawayMarkSmallBlock::new);
		DIVING_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("diving_allowed_seaway_mark_medium", DivingAllowedSeawayMarkMediumBlock::new);
		DIVING_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("diving_allowed_seaway_mark_big", DivingAllowedSeawayMarkBigBlock::new);
		JET_SKI_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("jet_ski_allowed_seaway_mark_small", JetSkiAllowedSeawayMarkSmallBlock::new);
		JET_SKI_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("jet_ski_allowed_seaway_mark_medium", JetSkiAllowedSeawayMarkMediumBlock::new);
		JET_SKI_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("jet_ski_allowed_seaway_mark_big", JetSkiAllowedSeawayMarkBigBlock::new);
		MOORING_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("mooring_allowed_seaway_mark_small", MooringAllowedSeawayMarkSmallBlock::new);
		MOORING_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("mooring_allowed_seaway_mark_medium", MooringAllowedSeawayMarkMediumBlock::new);
		MOORING_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("mooring_allowed_seaway_mark_big", MooringAllowedSeawayMarkBigBlock::new);
		MOTORBOAT_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("motorboat_allowed_seaway_mark_small", MotorboatAllowedSeawayMarkSmallBlock::new);
		MOTORBOAT_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("motorboat_allowed_seaway_mark_medium", MotorboatAllowedSeawayMarkMediumBlock::new);
		MOTORBOAT_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("motorboat_allowed_seaway_mark_big", MotorboatAllowedSeawayMarkBigBlock::new);
		PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("pleasure_boat_allowed_seaway_mark_small", PleasureBoatAllowedSeawayMarkSmallBlock::new);
		PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("pleasure_boat_allowed_seaway_mark_medium", PleasureBoatAllowedSeawayMarkMediumBlock::new);
		PLEASURE_BOAT_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("pleasure_boat_allowed_seaway_mark_big", PleasureBoatAllowedSeawayMarkBigBlock::new);
		SAILBOATS_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("sailboats_allowed_seaway_mark_small", SailboatAllowedSeawayMarkSmallBlock::new);
		SAILBOATS_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("sailboats_allowed_seaway_mark_medium", SailboatAllowedSeawayMarkMediumBlock::new);
		SAILBOATS_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("sailboats_allowed_seaway_mark_big", SailboatAllowedSeawayMarkBigBlock::new);
		WASHING_PLATFORM_SEAWAY_MARK_SMALL = REGISTRY.register("washing_platform_seaway_mark_small", WashingPlatformSeawayMarkSmallBlock::new);
		WASHING_PLATFORM_SEAWAY_MARK_MEDIUM = REGISTRY.register("washing_platform_seaway_mark_medium", WashingPlatformSeawayMarkMediumBlock::new);
		WASHING_PLATFORM_SEAWAY_MARK_BIG = REGISTRY.register("washing_platform_seaway_mark_big", WashingPlatformSeawayMarkBigBlock::new);
		WATER_SKI_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("water_ski_allowed_seaway_mark_small", WaterSkiAllowedSeawayMarkSmallBlock::new);
		WATER_SKI_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("water_ski_allowed_seaway_mark_medium", WaterSkiAllowedSeawayMarkMediumBlock::new);
		WATER_SKI_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("water_ski_allowed_seaway_mark_big", WaterSkiAllowedSeawayMarkBigBlock::new);
		WINDSURFING_ALLOWED_SEAWAY_MARK_SMALL = REGISTRY.register("windsurfing_allowed_seaway_mark_small", WindsurfingAllowedSeawayMarkSmallBlock::new);
		WINDSURFING_ALLOWED_SEAWAY_MARK_MEDIUM = REGISTRY.register("windsurfing_allowed_seaway_mark_medium", WindsurfingAllowedSeawayMarkMediumBlock::new);
		WINDSURFING_ALLOWED_SEAWAY_MARK_BIG = REGISTRY.register("windsurfing_allowed_seaway_mark_big", WindsurfingAllowedSeawayMarkBigBlock::new);
		LIANA_SIGN = REGISTRY.register("liana_sign", LianaSignBlock::new);
		LIANA_SIGN_1 = REGISTRY.register("liana_sign_1", LianaSign1Block::new);
		ANCHORING_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("anchoring_prohibited_seaway_mark_small", AnchoringProhibitedSeawayMarkSmallBlock::new);
		ANCHORING_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("anchoring_prohibited_seaway_mark_medium", AnchoringProhibitedSeawayMarkMediumBlock::new);
		ANCHORING_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("anchoring_prohibited_seaway_mark_big", AnchoringProhibitedSeawayMarkBigBlock::new);
		DIVING_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("diving_prohibited_seaway_mark_small", DivingProhibitedSeawayMarkSmallBlock::new);
		DIVING_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("diving_prohibited_seaway_mark_medium", DivingProhibitedSeawayMarkMediumBlock::new);
		DIVING_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("diving_prohibited_seaway_mark_big", DivingProhibitedSeawayMarkBigBlock::new);
		JET_SKI_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("jet_ski_prohibited_seaway_mark_small", JetSkiProhibitedSeawayMarkSmallBlock::new);
		JET_SKI_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("jet_ski_prohibited_seaway_mark_medium", JetSkiProhibitedSeawayMarkMediumBlock::new);
		JET_SKI_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("jet_ski_prohibited_seaway_mark_big", JetSkiProhibitedSeawayMarkBigBlock::new);
		GOING_ASHORE_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("going_ashore_prohibited_seaway_mark_small", GoingAshoreProhibitedSeawayMarkSmallBlock::new);
		GOING_ASHORE_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("going_ashore_prohibited_seaway_mark_medium", GoingAshoreProhibitedSeawayMarkMediumBlock::new);
		GOING_ASHORE_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("going_ashore_prohibited_seaway_mark_big", GoingAshoreProhibitedSeawayMarkBigBlock::new);
		MOORING_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("mooring_prohibited_seaway_mark_small", MooringProhibitedSeawayMarkSmallBlock::new);
		MOORING_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("mooring_prohibited_seaway_mark_medium", MooringProhibitedSeawayMarkMediumBlock::new);
		MOORING_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("mooring_prohibited_seaway_mark_big", MooringProhibitedSeawayMarkBigBlock::new);
		MOTORBOAT_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("motorboat_prohibited_seaway_mark_small", MotorboatProhibitedSeawayMarkSmallBlock::new);
		MOTORBOAT_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("motorboat_prohibited_seaway_mark_medium", MotorboatProhibitedSeawayMarkMediumBlock::new);
		MOTORBOAT_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("motorboat_prohibited_seaway_mark_big", MotorboatProhibitedSeawayMarkBigBlock::new);
		PARKING_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("parking_prohibited_seaway_mark_small", ParkingProhibitedSeawayMarkSmallBlock::new);
		PARKING_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("parking_prohibited_seaway_mark_medium", ParkingProhibitedSeawayMarkMediumBlock::new);
		PARKING_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("parking_prohibited_seaway_mark_big", ParkingProhibitedSeawayMarkBigBlock::new);
		PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("pleasure_craft_prohibited_seaway_mark_small", PleasureCraftProhibitedSeawayMarkSmallBlock::new);
		PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("pleasure_craft_prohibited_seaway_mark_medium", PleasureCraftProhibitedSeawayMarkMediumBlock::new);
		PLEASURE_CRAFT_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("pleasure_craft_prohibited_seaway_mark_big", PleasureCraftProhibitedSeawayMarkBigBlock::new);
		SAILBOATS_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("sailboats_prohibited_seaway_mark_small", SailboatProhibitedSeawayMarkSmallBlock::new);
		SAILBOATS_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("sailboats_prohibited_seaway_mark_medium", SailboatProhibitedSeawayMarkMediumBlock::new);
		SAILBOATS_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("sailboats_prohibited_seaway_mark_big", SailboatProhibitedSeawayMarkBigBlock::new);
		SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("sea_traffic_prohibited_seaway_mark_small", SeaTrafficProhibitedSeawayMarkSmallBlock::new);
		SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("sea_traffic_prohibited_seaway_mark_medium", SeaTrafficProhibitedSeawayMarkMediumBlock::new);
		SEA_TRAFFIC_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("sea_traffic_prohibited_seaway_mark_big", SeaTrafficProhibitedSeawayMarkBigBlock::new);
		WATER_SKI_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("water_ski_prohibited_seaway_mark_small", WaterSkiProhibitedSeawayMarkSmallBlock::new);
		WATER_SKI_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("water_ski_prohibited_seaway_mark_medium", WaterSkiProhibitedSeawayMarkMediumBlock::new);
		WATER_SKI_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("water_ski_prohibited_seaway_mark_big", WaterSkiProhibitedSeawayMarkBigBlock::new);
		WINDSURFING_PROHIBITED_SEAWAY_MARK_SMALL = REGISTRY.register("windsurfing_prohibited_seaway_mark_small", WindsurfingProhibitedSeawayMarkSmallBlock::new);
		WINDSURFING_PROHIBITED_SEAWAY_MARK_MEDIUM = REGISTRY.register("windsurfing_prohibited_seaway_mark_medium", WindsurfingProhibitedSeawayMarkMediumBlock::new);
		WINDSURFING_PROHIBITED_SEAWAY_MARK_BIG = REGISTRY.register("windsurfing_prohibited_seaway_mark_big", WindsurfingProhibitedSeawayMarkBigBlock::new);
		CABLE_FERRY_SEAWAY_MARK_SMALL = REGISTRY.register("cable_ferry_seaway_mark_small", CableFerrySeawayMarkSmallBlock::new);
		CABLE_FERRY_SEAWAY_MARK_MEDIUM = REGISTRY.register("cable_ferry_seaway_mark_medium", CableFerrySeawayMarkMediumBlock::new);
		CABLE_FERRY_SEAWAY_MARK_BIG = REGISTRY.register("cable_ferry_seaway_mark_big", CableFerrySeawayMarkBigBlock::new);
		CONSTRUCTION_ZONE_SEAWAY_MARK_SMALL = REGISTRY.register("construction_zone_seaway_mark_small", ConstructionZoneSeawayMarkSmallBlock::new);
		CONSTRUCTION_ZONE_SEAWAY_MARK_MEDIUM = REGISTRY.register("construction_zone_seaway_mark_medium", ConstructionZoneSeawayMarkMediumBlock::new);
		CONSTRUCTION_ZONE_SEAWAY_MARK_BIG = REGISTRY.register("construction_zone_seaway_mark_big", ConstructionZoneSeawayMarkBigBlock::new);
		FISHING_GEAR_SEAWAY_MARK_SMALL = REGISTRY.register("fishing_gear_seaway_mark_small", FishingGearSeawayMarkSmallBlock::new);
		FISHING_GEAR_SEAWAY_MARK_MEDIUM = REGISTRY.register("fishing_gear_seaway_mark_medium", FishingGearSeawayMarkMediumBlock::new);
		FISHING_GEAR_SEAWAY_MARK_BIG = REGISTRY.register("fishing_gear_seaway_mark_big", FishingGearSeawayMarkBigBlock::new);
		GIVE_SOUND_SIGNAL_SEAWAY_MARK_SMALL = REGISTRY.register("give_sound_signal_seaway_mark_small", GiveSoundSignalSeawayMarkSmallBlock::new);
		GIVE_SOUND_SIGNAL_SEAWAY_MARK_MEDIUM = REGISTRY.register("give_sound_signal_seaway_mark_medium", GiveSoundSignalSeawayMarkMediumBlock::new);
		GIVE_SOUND_SIGNAL_SEAWAY_MARK_BIG = REGISTRY.register("give_sound_signal_seaway_mark_big", GiveSoundSignalSeawayMarkBigBlock::new);
		LIVE_WIRE_SEAWAY_MARK_SMALL = REGISTRY.register("live_wire_seaway_mark_small", LiveWireSeawayMarkSmallBlock::new);
		LIVE_WIRE_SEAWAY_MARK_MEDIUM = REGISTRY.register("live_wire_seaway_mark_medium", LiveWireSeawayMarkMediumBlock::new);
		LIVE_WIRE_SEAWAY_MARK_BIG = REGISTRY.register("live_wire_seaway_mark_big", LiveWireSeawayMarkBigBlock::new);
		MOVEABLE_BRIDGE_SEAWAY_MARK_SMALL = REGISTRY.register("moveable_bridge_seaway_mark_small", MoveableBridgeSeawayMarkSmallBlock::new);
		MOVEABLE_BRIDGE_SEAWAY_MARK_MEDIUM = REGISTRY.register("moveable_bridge_seaway_mark_medium", MoveableBridgeSeawayMarkMediumBlock::new);
		MOVEABLE_BRIDGE_SEAWAY_MARK_BIG = REGISTRY.register("moveable_bridge_seaway_mark_big", MoveableBridgeSeawayMarkBigBlock::new);
		ONE_WAY_TRAFFIC_SEAWAY_MARK_SMALL = REGISTRY.register("one_way_traffic_seaway_mark_small", OneWayTrafficSeawayMarkSmallBlock::new);
		ONE_WAY_TRAFFIC_SEAWAY_MARK_MEDIUM = REGISTRY.register("one_way_traffic_seaway_mark_medium", OneWayTrafficSeawayMarkMediumBlock::new);
		ONE_WAY_TRAFFIC_SEAWAY_MARK_BIG = REGISTRY.register("one_way_traffic_seaway_mark_big", OneWayTrafficSeawayMarkBigBlock::new);
		OTHER_HAZARD_SEAWAY_MARK_SMALL = REGISTRY.register("other_hazard_seaway_mark_small", OtherHazardSeawayMarkSmallBlock::new);
		OTHER_HAZARD_SEAWAY_MARK_MEDIUM = REGISTRY.register("other_hazard_seaway_mark_medium", OtherHazardSeawayMarkMediumBlock::new);
		OTHER_HAZARD_SEAWAY_MARK_BIG = REGISTRY.register("other_hazard_seaway_mark_big", OtherHazardSeawayMarkBigBlock::new);
		STOP_LINE_SEAWAY_MARK_SMALL = REGISTRY.register("stop_line_seaway_mark_small", StopLineSeawayMarkSmallBlock::new);
		STOP_LINE_SEAWAY_MARK_MEDIUM = REGISTRY.register("stop_line_seaway_mark_medium", StopLineSeawayMarkMediumBlock::new);
		STOP_LINE_SEAWAY_MARK_BIG = REGISTRY.register("stop_line_seaway_mark_big", StopLineSeawayMarkBigBlock::new);
		SWIMMING_AREA_SEAWAY_MARK_SMALL = REGISTRY.register("swimming_area_seaway_mark_small", SwimmingAreaSeawayMarkSmallBlock::new);
		SWIMMING_AREA_SEAWAY_MARK_MEDIUM = REGISTRY.register("swimming_area_seaway_mark_medium", SwimmingAreaSeawayMarkMediumBlock::new);
		SWIMMING_AREA_SEAWAY_MARK_BIG = REGISTRY.register("swimming_area_seaway_mark_big", SwimmingAreaSeawayMarkBigBlock::new);
		MAX_SPEED_SEAWAY_MARK_SMALL = REGISTRY.register("max_speed_seaway_mark_small", MaxSpeedSeawayMarkSmallBlock::new);
		MAX_SPEED_SEAWAY_MARK_MEDIUM = REGISTRY.register("max_speed_seaway_mark_medium", MaxSpeedSeawayMarkMediumBlock::new);
		MAX_SPEED_SEAWAY_MARK_BIG = REGISTRY.register("max_speed_seaway_mark_big", MaxSpeedSeawayMarkBigBlock::new);
		REFER_TO_CHART_SEAWAY_MARK_SMALL = REGISTRY.register("refer_to_chart_seaway_mark_small", ReferToChartSeawayMarkSmallBlock::new);
		REFER_TO_CHART_SEAWAY_MARK_MEDIUM = REGISTRY.register("refer_to_chart_seaway_mark_medium", ReferToChartSeawayMarkMediumBlock::new);
		REFER_TO_CHART_SEAWAY_MARK_BIG = REGISTRY.register("refer_to_chart_seaway_mark_big", ReferToChartSeawayMarkBigBlock::new);
		DISTANCE_FROM_MARK_M_SEAWAY_MARK_SMALL = REGISTRY.register("distance_from_mark_m_seaway_mark_small", DistanceFromMarkMSeawayMarkSmallBlock::new);
		DISTANCE_FROM_MARK_M_SEAWAY_MARK_MEDIUM = REGISTRY.register("distance_from_mark_m_seaway_mark_medium", DistanceFromMarkMSeawayMarkMediumBlock::new);
		DISTANCE_FROM_MARK_M_SEAWAY_MARK_BIG = REGISTRY.register("distance_from_mark_m_seaway_mark_big", DistanceFromMarkMSeawayMarkBigBlock::new);
		DISTANCE_FROM_MARK_NM_SEAWAY_MARK_SMALL = REGISTRY.register("distance_from_mark_nm_seaway_mark_small", DistanceFromMarkNMSeawayMarkSmallBlock::new);
		DISTANCE_FROM_MARK_NM_SEAWAY_MARK_MEDIUM = REGISTRY.register("distance_from_mark_nm_seaway_mark_medium", DistanceFromMarkNMSeawayMarkMediumBlock::new);
		DISTANCE_FROM_MARK_NM_SEAWAY_MARK_BIG = REGISTRY.register("distance_from_mark_nm_seaway_mark_big", DistanceFromMarkNMSeawayMarkBigBlock::new);
		DISTANCE_TO_SEAWAY_MARK_SMALL = REGISTRY.register("distance_to_seaway_mark_small", DistanceToSeawayMarkSmallBlock::new);
		DISTANCE_TO_SEAWAY_MARK_MEDIUM = REGISTRY.register("distance_to_seaway_mark_medium", DistanceToSeawayMarkMediumBlock::new);
		DISTANCE_TO_SEAWAY_MARK_BIG = REGISTRY.register("distance_to_seaway_mark_big", DistanceToSeawayMarkBigBlock::new);
		BOAT_WASHING_SEAWAY_MARK_SMALL = REGISTRY.register("boat_washing_seaway_mark_small", BoatWashingSeawayMarkSmallBlock::new);
		BOAT_WASHING_SEAWAY_MARK_MEDIUM = REGISTRY.register("boat_washing_seaway_mark_medium", BoatWashingSeawayMarkMediumBlock::new);
		BOAT_WASHING_SEAWAY_MARK_BIG = REGISTRY.register("boat_washing_seaway_mark_big", BoatWashingSeawayMarkBigBlock::new);
		SHORE_POWER_SEAWAY_MARK_SMALL = REGISTRY.register("shore_power_seaway_mark_small", ShorePowerSeawayMarkSmallBlock::new);
		SHORE_POWER_SEAWAY_MARK_MEDIUM = REGISTRY.register("shore_power_seaway_mark_medium", ShorePowerSeawayMarkMediumBlock::new);
		SHORE_POWER_SEAWAY_MARK_BIG = REGISTRY.register("shore_power_seaway_mark_big", ShorePowerSeawayMarkBigBlock::new);
		NO_WAKE_SEAWAY_MARK_SMALL = REGISTRY.register("no_wake_seaway_mark_small", NoWakeSeawayMarkSmallBlock::new);
		NO_WAKE_SEAWAY_MARK_MEDIUM = REGISTRY.register("no_wake_seaway_mark_medium", NoWakeSeawayMarkMediumBlock::new);
		NO_WAKE_SEAWAY_MARK_BIG = REGISTRY.register("no_wake_seaway_mark_big", NoWakeSeawayMarkBigBlock::new);
		RESTRICTED_HEIGHT_SEAWAY_MARK_SMALL = REGISTRY.register("restricted_height_seaway_mark_small", RestrictedHeightSeawayMarkSmallBlock::new);
		RESTRICTED_HEIGHT_SEAWAY_MARK_MEDIUM = REGISTRY.register("restricted_height_seaway_mark_medium", RestrictedHeightSeawayMarkMediumBlock::new);
		RESTRICTED_HEIGHT_SEAWAY_MARK_BIG = REGISTRY.register("restricted_height_seaway_mark_big", RestrictedHeightSeawayMarkBigBlock::new);
		RESTRICTED_WIDTH_SEAWAY_MARK_SMALL = REGISTRY.register("restricted_width_seaway_mark_small", RestrictedWidthSeawayMarkSmallBlock::new);
		RESTRICTED_WIDTH_SEAWAY_MARK_MEDIUM = REGISTRY.register("restricted_width_seaway_mark_medium", RestrictedWidthSeawayMarkMediumBlock::new);
		RESTRICTED_WIDTH_SEAWAY_MARK_BIG = REGISTRY.register("restricted_width_seaway_mark_big", RestrictedWidthSeawayMarkBigBlock::new);
		RESTRICTED_DEPTH_SEAWAY_MARK_SMALL = REGISTRY.register("restricted_depth_seaway_mark_small", RestrictedDepthSeawayMarkSmallBlock::new);
		RESTRICTED_DEPTH_SEAWAY_MARK_MEDIUM = REGISTRY.register("restricted_depth_seaway_mark_medium", RestrictedDepthSeawayMarkMediumBlock::new);
		RESTRICTED_DEPTH_SEAWAY_MARK_BIG = REGISTRY.register("restricted_depth_seaway_mark_big", RestrictedDepthSeawayMarkBigBlock::new);
		LEADING_LINE_BOTTOM_SEAWAY_MARK_SMALL = REGISTRY.register("leading_line_bottom_seaway_mark_small", LeadingLineBottomSeawayMarkSmallBlock::new);
		LEADING_LINE_BOTTOM_SEAWAY_MARK_MEDIUM = REGISTRY.register("leading_line_bottom_seaway_mark_medium", LeadingLineBottomSeawayMarkMediumBlock::new);
		LEADING_LINE_BOTTOM_SEAWAY_MARK_BIG = REGISTRY.register("leading_line_bottom_seaway_mark_big", LeadingLineBottomSeawayMarkBigBlock::new);
		LEADING_LINE_TOP_SEAWAY_MARK_SMALL = REGISTRY.register("leading_line_top_seaway_mark_small", LeadingLineTopSeawayMarkSmallBlock::new);
		LEADING_LINE_TOP_SEAWAY_MARK_MEDIUM = REGISTRY.register("leading_line_top_seaway_mark_medium", LeadingLineTopSeawayMarkMediumBlock::new);
		LEADING_LINE_TOP_SEAWAY_MARK_BIG = REGISTRY.register("leading_line_top_seaway_mark_big", LeadingLineTopSeawayMarkBigBlock::new);
		SIGN_MOUNT_BASE_SMALL = REGISTRY.register("sign_mount_base_small", SignMountBaseSmallBlock::new);
		SIGN_MOUNT_BASE_MEDIUM = REGISTRY.register("sign_mount_base_medium", SignMountBaseMediumBlock::new);
		SIGN_MOUNT_BASE_BIG = REGISTRY.register("sign_mount_base_big", SignMountBaseBigBlock::new);
		SIGN_MOUNT_SMALL = REGISTRY.register("sign_mount_small", SignMountSmallBlock::new);
		SIGN_MOUNT_MEDIUM = REGISTRY.register("sign_mount_medium", SignMountMediumBlock::new);
		SIGN_MOUNT_BIG = REGISTRY.register("sign_mount_big", SignMountBigBlock::new);
		THIN_SIGN_MOUNT_SMALL = REGISTRY.register("thin_sign_mount_small", ThinSignMountSmallBlock::new);
		THIN_SIGN_MOUNT_MEDIUM = REGISTRY.register("thin_sign_mount_medium", ThinSignMountMediumBlock::new);
		THIN_SIGN_MOUNT_BIG = REGISTRY.register("thin_sign_mount_big", ThinSignMountBigBlock::new);
	}
}